name: Validar Calidad de Datos

# Se activa cuando haces un "push" o un "pull request" a la rama main 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código de tu repositorio en el servidor de GitHub
    - uses: actions/checkout@v3

    # 2. Prepara el entorno de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Instala las librerías necesarias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Ejecuta tu script de prueba para asegurar que no hay errores 
    - name: Run Data Quality Check
      run: python main.py